# Form implementation generated from reading ui file 'DashWindow.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.lbl_Tach1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Tach1.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_Tach1.setPixmap(QtGui.QPixmap("IMAGE/Tach.png"))
        self.lbl_Tach1.setObjectName("lbl_Tach1")
        self.lbl_Tach2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_Tach2.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_Tach2.setPixmap(QtGui.QPixmap("IMAGE/Tach2.png"))
        self.lbl_Tach2.setObjectName("lbl_Tach2")
        self.lbl_LINES = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_LINES.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_LINES.setPixmap(QtGui.QPixmap("IMAGE/LINES_V3.png"))
        self.lbl_LINES.setObjectName("lbl_LINES")
        self.lbl_888_IN_CURR = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_888_IN_CURR.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_888_IN_CURR.setPixmap(QtGui.QPixmap("IMAGE/888_IN_CURR.png"))
        self.lbl_888_IN_CURR.setObjectName("lbl_888_IN_CURR")

        self.lbl_888_OUT_CURRENT = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_888_OUT_CURRENT.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_888_OUT_CURRENT.setPixmap(QtGui.QPixmap("IMAGE/888_OUT_CURR.png"))
        self.lbl_888_OUT_CURRENT.setObjectName("lbl_888_OUT_CURRENT")
        self.lbl_num_R = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_num_R.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_num_R.setPixmap(QtGui.QPixmap("IMAGE/num_R.png"))
        self.lbl_num_R.setObjectName("lbl_num_R")
        self.lbl_num_1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_num_1.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_num_1.setPixmap(QtGui.QPixmap("IMAGE/num_1.png"))
        self.lbl_num_1.setObjectName("lbl_num_1")
        self.lbl_num_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_num_2.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_num_2.setPixmap(QtGui.QPixmap("IMAGE/num_2.png"))
        self.lbl_num_2.setObjectName("lbl_num_2")
        self.lbl_num_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_num_3.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_num_3.setPixmap(QtGui.QPixmap("IMAGE/num_3.png"))
        self.lbl_num_3.setObjectName("lbl_num_3")

        self.lbl_MODE_M = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_MODE_M.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_MODE_M.setPixmap(QtGui.QPixmap("IMAGE/MODE_M_V3.png"))
        self.lbl_MODE_M.setObjectName("lbl_MODE_M")
        self.lbl_MODE_A = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_MODE_A.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_MODE_A.setPixmap(QtGui.QPixmap("IMAGE/MODE_A_V3.png"))
        self.lbl_MODE_A.setObjectName("lbl_MODE_A")
        self.lbl_RPM_888 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_RPM_888.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_RPM_888.setPixmap(QtGui.QPixmap("IMAGE/RPM_888.png"))
        self.lbl_RPM_888.setObjectName("lbl_RPM_888")
        self.lbl_KM_H_888 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_KM_H_888.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_KM_H_888.setPixmap(QtGui.QPixmap("IMAGE/KM_H_888.png"))
        self.lbl_KM_H_888.setObjectName("lbl_KM_H_888")
        self.lbl_RPM = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_RPM.setGeometry(QtCore.QRect(0, 0, 1920, 1080))

        self.lbl_RPM.setObjectName("lbl_RPM")
        self.lbl_KM_H = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_KM_H.setGeometry(QtCore.QRect(0, 0, 1920, 1080))

        self.lbl_KM_H.setObjectName("lbl_KM_H")

        self.lbl_888_T_MOTEUR = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_888_T_MOTEUR.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_888_T_MOTEUR.setPixmap(QtGui.QPixmap("IMAGE/888_T_MOTEUR.png"))
        self.lbl_888_T_MOTEUR.setObjectName("lbl_888_T_MOTEUR")
        self.lbl_888_T_MR = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_888_T_MR.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_888_T_MR.setPixmap(QtGui.QPixmap("IMAGE/888_T_MR.png"))
        self.lbl_888_T_MR.setObjectName("lbl_888_T_MR")
        self.lbl_888_T_DRIVE = QtWidgets.QLabel(parent=self.centralwidget)
        self.lbl_888_T_DRIVE.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.lbl_888_T_DRIVE.setPixmap(QtGui.QPixmap("IMAGE/888_T_DIRVE.png"))
        self.lbl_888_T_DRIVE.setObjectName("lbl_888_T_DRIVE")

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
